# mypy.ini - before
[mypy]
ignore_missing_imports = True

[mypy]
no_error_summary = True

# mypy.ini - after
[mypy]
ignore_missing_imports = True
no_error_summary = True

[mypy]
exclude = ^(migrations|alembic)/env.py$
